import { Type } from "@sinclair/typebox"
import type { Api } from "spac"
import BingSearchCoffeeExample from "./examples/bing-search-coffee.json"

export function registerBing(api: Api) {
  api.group("/search", (g) => {
    g.get("/bing")
      .query(Type.Object({
        q: Type.String({ description: "Parameter defines the search query. You can use anything that you would use in a regular Bing search. (e.g., `'query'`, `NOT`, `OR`, `site:`, `filetype:`, `near:`, `ip:`, `loc:`, `feed:` etc.)." }),
        location: Type.Optional(Type.String({ description: "Parameter defines from where you want the search to originate. If several locations match the location requested, we'll pick the most popular one. Head to the /locations.json API if you need more precise control. The location and uule parameters can't be used together. It is recommended to specify location at the city level in order to simulate a real user’s search. If location is omitted, the search may take on the location of the proxy." })),
        lat: Type.Optional(Type.Number({ description: "Defines a GPS latitude for the search origin" })),
        lon: Type.Optional(Type.Number({ description: "Defines a GPS longitude for the search origin" })),
        mkt: Type.Optional(Type.String({ description: "The market where the results come from (e.g. `en-US`). Typically, mkt is the country where the user is making the request from. However, it could be a different country if the user is not located in a country where Bing delivers results. The market must be in the form -. For example, en-US. The string is case insensitive. For a list of possible market values, see Market Codes. NOTE: If known, you are encouraged to always specify the market. Specifying the market helps Bing route the request and return an appropriate and optimal response. If you specify a market that is not listed in Market Codes, Bing uses a best fit market code based on an internal mapping that is subject to change. This parameter and the cc query parameter are mutually exclusive—do not specify both.. Valid values include: es-ar, en-au, de-at, nl-be, fr-be, pt-br, en-ca, fr-ca, es-cl, da-dk, and 28 more" })),
        cc: Type.Optional(Type.String({ description: "Parameter defines the country to search from. It follows the 2-character ISO\\_3166-1 format. (e.g., `us` for United States, `de` for Germany, `gb` for United Kingdom, etc.).. Valid values include: AR, AU, AT, BE, BR, CA, CL, DK, FI, FR, and 26 more" })),
        first: Type.Optional(Type.Number({ description: "Parameter controls the offset of the organic results. This parameter defaults to `1`. (e.g., `first=10` will move the 10th organic result to the first position)." })),
        safeSearch: Type.Optional(Type.Union([Type.Literal("off"), Type.Literal("moderate"), Type.Literal("strict")], { description: "Parameter defines the level of filtering for adult content. It can be set to: `Off` to return webpages with adult text, images, or videos. `Moderate` to return webpages with adult text, but not adult images or videos. `Strict` to not return webpages with adult text, images, or videos." })),
        filters: Type.Optional(Type.String({ description: "Parameter allows usage of a more complex filtering options such as filtering by date range `ex1:\"ez5_18169_18230\"` or using a specific display filters such as `ufn:\"Wunderman+Thompson\"+sid:\"5bede9a2-1bda-9887-e6eb-30b1b8b6b513\"+catguid:\"5bede9a2-1bda-9887-e6eb-30b1b8b6b513_cfb02057\"+segment:\"generic.carousel\"+entitysegment:\"Organization\"`. Exact values can be constructed by using Bing search and copying `filters` query parameter." })),
        device: Type.Optional(Type.String({ description: "Parameter defines the device to use to get the results. It can be set to `desktop` (default) to use a regular browser, `tablet` to use a tablet browser (currently using iPads), or `mobile` to use a mobile browser." })),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing search results" }))
      .summary("Bing")
      .description("Search via Bing. Real API: GET /search.json?engine=bing")
      .operationId("searchBing")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing")
      .extension("x-serpapi-real-path", "/search.json")
      .example("search-coffee", { summary: "Bing example: search coffee", value: BingSearchCoffeeExample })

    g.get("/bing_copilot")
      .query(Type.Object({
        q: Type.String({ description: "Parameter defines the search query for Bing Copilot. You can use anything that you would use in a regular Bing Copilot search." }),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing Copilot results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing Copilot search results" }))
      .summary("Bing Copilot")
      .description("Search via Bing Copilot. Real API: GET /search.json?engine=bing_copilot")
      .operationId("searchBingCopilot")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_copilot")
      .extension("x-serpapi-real-path", "/search.json")

    g.get("/bing_images")
      .query(Type.Object({
        q: Type.String({ description: "Parameter defines the search query. You can use anything that you would use in a regular Bing Images search." }),
        mkt: Type.Optional(Type.String({ description: "The market where the results come from (e.g. `en-US`). Typically, mkt is the country where the user is making the request from. However, it could be a different country if the user is not located in a country where Bing Images API delivers results. The market must be in the form -. For example, en-US. The string is case insensitive. For a list of possible market values, see Market Codes. NOTE: If known, you are encouraged to always specify the market. Specifying the market helps Bing route the request and return an appropriate and optimal response. If you specify a market that is not listed in Market Codes, Bing Images API uses a best fit market code based on an internal mapping that is subject to change. This parameter and the cc query parameter are mutually exclusive—do not specify both.. Valid values include: es-ar, en-au, de-at, nl-be, fr-be, pt-br, en-ca, fr-ca, es-cl, da-dk, and 28 more" })),
        cc: Type.Optional(Type.String({ description: "Parameter defines the country to search from. It follows the 2-character ISO\\_3166-1 format. (e.g., `us` for United States, `de` for Germany, `gb` for United Kingdom, etc.).. Valid values include: AR, AU, AT, BE, BR, CA, CL, DK, FI, FR, and 26 more" })),
        first: Type.Optional(Type.Number({ description: "Parameter controls the offset of the organic results. This parameter defaults to `1`. (e.g., `first=10` will move the 10th organic result to the first position)." })),
        count: Type.Optional(Type.Number({ description: "Parameter controls the number of results per page. This parameter is only a suggestion and might not reflect the returned results." })),
        imagesize: Type.Optional(Type.Union([Type.Literal("small"), Type.Literal("medium"), Type.Literal("large"), Type.Literal("wallpaper")], { description: "Parameter is used for filtering images by size. It can be set to: `small` - Small `medium` - Medium `large` - Large `wallpaper` - Extra Large" })),
        color2: Type.Optional(Type.Union([Type.Literal("color"), Type.Literal("bw"), Type.Literal("FGcls_RED"), Type.Literal("FGcls_ORANGE"), Type.Literal("FGcls_YELLOW"), Type.Literal("FGcls_GREEN"), Type.Literal("FGcls_TEAL"), Type.Literal("FGcls_BLUE"), Type.Literal("FGcls_PURPLE"), Type.Literal("FGcls_PINK"), Type.Literal("FGcls_BROWN"), Type.Literal("FGcls_BLACK"), Type.Literal("FGcls_GRAY"), Type.Literal("FGcls_WHITE")], { description: "Parameter is used for filtering images by color. It can be set to: `color` - Color Only `bw` - Black & white `FGcls_RED` - Red `FGcls_ORANGE` - Orange `FGcls_YELLOW` - Yellow `FGcls_GREEN` - Green `FGcls_TEAL` - Teal `FGcls_BLUE` - Blue `FGcls_PURPLE` - Purple `FGcls_PINK` - Pink `FGcls_BROWN` - Brown `FGcls_BLACK` - Black `FGcls_GRAY` - Gray `FGcls_WHITE` - White" })),
        photo: Type.Optional(Type.Union([Type.Literal("photo"), Type.Literal("clipart"), Type.Literal("linedrawing"), Type.Literal("animatedgif"), Type.Literal("animatedgifhttps"), Type.Literal("transparent"), Type.Literal("shopping")], { description: "Parameter is used for filtering images by image type. It can be set to: `photo` - Photo `clipart` - Clipart `linedrawing` - Line Drawing `animatedgif` - Animated GIF `animatedgifhttps` - Animated GIF HTTPS `transparent` - Transparent `shopping` - Shopping, return only images that contain items where Bing knows of a merchant that is selling the items" })),
        aspect: Type.Optional(Type.Union([Type.Literal("square"), Type.Literal("wide"), Type.Literal("tall")], { description: "Parameter is used for filtering images by layout. It can be set to: `square` - Square `wide` - Wide `tall` - Tall" })),
        face: Type.Optional(Type.Union([Type.Literal("face"), Type.Literal("portrait")], { description: "Parameter is used for filtering images by people. It can be set to: `face` - Faces Only `portrait` - Head & Shoulders" })),
        age: Type.Optional(Type.Union([Type.Literal("lt1440"), Type.Literal("lt10080"), Type.Literal("lt43200"), Type.Literal("lt525600")], { description: "Parameter is used for filtering images by date. It can be set to: `lt1440` - Past 24 hours `lt10080` - Past week `lt43200` - Past month `lt525600` - Past year" })),
        license: Type.Optional(Type.Union([Type.Literal("Type-Any"), Type.Literal("L1"), Type.Literal("L2_L3_L4_L5_L6_L7"), Type.Literal("L2_L3_L4"), Type.Literal("L2_L3_L5_L6"), Type.Literal("L2_L3")], { description: "Parameter is used for filtering images by license. It can be set to: `Type-Any` - All Creative Commons `L1` - Public Domain `L2_L3_L4_L5_L6_L7` - Free to share and use `L2_L3_L4` - Free to share and use commercially `L2_L3_L5_L6` - Free to modify, share and use `L2_L3` - Free to modify, share, and use commercially" })),
        device: Type.Optional(Type.String({ description: "Parameter defines the device to use to get the results. It can be set to `desktop` (default) to use a regular browser, `tablet` to use a tablet browser (currently using iPads), or `mobile` to use a mobile browser." })),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing Images results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing Images search results" }))
      .summary("Bing Images")
      .description("Search via Bing Images. Real API: GET /search.json?engine=bing_images")
      .operationId("searchBingImages")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_images")
      .extension("x-serpapi-real-path", "/search.json")

    g.get("/bing_maps")
      .query(Type.Object({
        q: Type.String({ description: "Parameter defines the search query. You can use anything that you would use in a regular Bing Maps search." }),
        cp: Type.Optional(Type.String({ description: "Parameter defines GPS coordinates of location where you want your q (query) to be applied. It has to be constructed in the next sequence: `latitude` + `~` + `longitude` This will form a string that looks like this: e.g. `40.7455096~-74.0083012`." })),
        setlang: Type.Optional(Type.String({ description: "Parameter defines the language to search with. It follows the 2-character ISO\\_3166-1 format. (e.g., `us` for United States, `de` for Germany, `gb` for United Kingdom, etc.). You can view all supported language codes on Bing Maps.. Valid values include: ar, eu, bn, bg, ca, zh-hans, zh-hant, hr, cs, da, and 40 more" })),
        place_id: Type.Optional(Type.String({ description: "Parameter defines the unique reference to a place on a Bing Map. Place IDs are available for most locations, including businesses, landmarks, parks, and intersections. You can find the place\\_id using our Bing Maps API and Bing Local Pack API. place\\_id can be used without any other optional parameter including q parameter." })),
        first: Type.Optional(Type.Number({ description: "Parameter controls the offset of the local results. This parameter defaults to `0`. (e.g. When `count=10`, the second page result start from `first=10`)." })),
        count: Type.Optional(Type.Number({ description: "Parameter controls the number of results per page. This parameter is only a suggestion and might not reflect the returned results. Maximum results per page is `30`" })),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing Maps results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing Maps search results" }))
      .summary("Bing Maps")
      .description("Search via Bing Maps. Real API: GET /search.json?engine=bing_maps")
      .operationId("searchBingMaps")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_maps")
      .extension("x-serpapi-real-path", "/search.json")

    g.get("/bing_news")
      .query(Type.Object({
        q: Type.String({ description: "Parameter defines the search query. You can use anything that you would use in a regular Bing search. (e.g., `'query'`, `NOT`, `OR`, `site:`, `filetype:`, `near:`, `ip:`, `loc:`, `feed:` etc.)." }),
        mkt: Type.Optional(Type.String({ description: "The market where the results come from (e.g. `en-US`). Typically, mkt is the country where the user is making the request from. However, it could be a different country if the user is not located in a country where Bing delivers results. The market must be in the form -. For example, en-US. The string is case insensitive. For a list of possible market values, see Market Codes. NOTE: If known, you are encouraged to always specify the market. Specifying the market helps Bing route the request and return an appropriate and optimal response. If you specify a market that is not listed in Market Codes, Bing uses a best fit market code based on an internal mapping that is subject to change. This parameter and the cc query parameter are mutually exclusive—do not specify both.. Valid values include: es-ar, en-au, de-at, nl-be, fr-be, pt-br, en-ca, fr-ca, es-cl, da-dk, and 27 more" })),
        cc: Type.Optional(Type.String({ description: "Parameter defines the country to search from. It follows the 2-character ISO\\_3166-1 format. (e.g., `us` for United States, `de` for Germany, `gb` for United Kingdom, etc.).. Valid values include: AR, AU, AT, BE, BR, CA, CL, DK, FI, FR, and 25 more" })),
        first: Type.Optional(Type.Number({ description: "Parameter controls the offset of the organic results. This parameter defaults to `1`. (e.g., `first=10` will move the 10th organic result to the first position)." })),
        count: Type.Optional(Type.Number({ description: "Parameter controls the number of results per page. This parameter is only a suggestion and might not reflect actual results returned." })),
        qft: Type.Optional(Type.Union([Type.Literal("interval=\"4\""), Type.Literal("interval=\"7\""), Type.Literal("interval=\"8\""), Type.Literal("interval=\"9\""), Type.Literal("sortbydate=\"1\"")], { description: "Parameter defines results sorted by date. If the parameter is not set, it will default to the \"Best match\" sorting, otherwise, if set to: e.g. `interval=\"4\"`, it will show results from the past hour. Other options are: `interval=\"7\"`: Past 24 hours, `interval=\"8\"`: Past 7 days, `interval=\"9\"`: Past 30 days, `sortbydate=\"1\"`: Most Recent" })),
        safeSearch: Type.Optional(Type.Union([Type.Literal("off"), Type.Literal("moderate"), Type.Literal("strict")], { description: "Parameter defines the level of filtering for adult content. It can be set to: `Off` to return webpages with adult text, images, or videos. `Moderate` to return webpages with adult text, but not adult images or videos. `Strict` to not return webpages with adult text, images, or videos." })),
        device: Type.Optional(Type.String({ description: "Parameter defines the device to use to get the results. It can be set to `desktop` (default) to use a regular browser, `tablet` to use a tablet browser (currently using iPads), or `mobile` to use a mobile browser." })),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing News results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing News search results" }))
      .summary("Bing News")
      .description("Search via Bing News. Real API: GET /search.json?engine=bing_news")
      .operationId("searchBingNews")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_news")
      .extension("x-serpapi-real-path", "/search.json")

    g.get("/bing_product")
      .query(Type.Object({
        product_token: Type.String({ description: "Parameter defines the token needed to retrieve specific product details. The token is generated by SerpApi using our Bing Shopping API." }),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing Product results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing Product search results" }))
      .summary("Bing Product")
      .description("Search via Bing Product. Real API: GET /search.json?engine=bing_product")
      .operationId("searchBingProduct")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_product")
      .extension("x-serpapi-real-path", "/search.json")

    g.get("/bing_reverse_image")
      .query(Type.Object({
        image_url: Type.String({ description: "Parameter defines the URL for an image to perform the reverse image search. NOTE: The image's width and height must each be 4,000 pixels or less." }),
        mkt: Type.Optional(Type.String({ description: "The market where the results come from (e.g. `en-US`). Typically, mkt is the country where the user is making the request from. However, it could be a different country if the user is not located in a country where Bing Reverse Image API delivers results. The market must be in the form -. For example, en-US. The string is case insensitive. For a list of possible market values, see Market Codes. NOTE: If known, you are encouraged to always specify the market. Specifying the market helps Bing route the request and return an appropriate and optimal response. If you specify a market that is not listed in Market Codes, Bing Reverse Image API uses a best fit market code based on an internal mapping that is subject to change.. Valid values include: es-ar, en-au, de-at, nl-be, fr-be, pt-br, en-ca, fr-ca, es-cl, da-dk, and 28 more" })),
        cat: Type.Optional(Type.Number({ description: "Parameter is used to crop the image and perform the reverse search on the cropped part of the image. For example, `0.3` means cropping 30% from the top. The minimum and maximum for this coordinate are `0` and `1`, respectively." })),
        cal: Type.Optional(Type.Number({ description: "Parameter is used to crop the image and perform the reverse search on the cropped part of the image. For example, `0.3` means cropping 30% from the left. The minimum and maximum for this coordinate are `0` and `1`, respectively." })),
        car: Type.Optional(Type.Number({ description: "Parameter is used to crop the image and perform the reverse search on the cropped part of the image. For example, `0.8` means cropping the right, 80% from the left. The minimum and maximum for this coordinate are `0` and `1`, respectively." })),
        cab: Type.Optional(Type.Number({ description: "Parameter is used to crop the image and perform the reverse search on the cropped part of the image. For example, `0.8` means cropping the bottom, 80% from the top. The minimum and maximum for this coordinate are `0` and `1`, respectively." })),
        next_page_token: Type.Optional(Type.String({ description: "Parameter defines the next page token. It is used for retrieving the next page results." })),
        count: Type.Optional(Type.Number({ description: "Parameter controls the number of results per page. This parameter defaults to `35`. This parameter is only a suggestion and might not reflect the returned results. The minimum and maximum for this parameter are `0` and `150`, respectively." })),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing Reverse Image results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing Reverse Image search results" }))
      .summary("Bing Reverse Image")
      .description("Search via Bing Reverse Image. Real API: GET /search.json?engine=bing_reverse_image")
      .operationId("searchBingReverseImage")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_reverse_image")
      .extension("x-serpapi-real-path", "/search.json")

    g.get("/bing_shopping")
      .query(Type.Object({
        q: Type.String({ description: "Parameter defines the search query. You can use anything that you would use in a regular Bing Shopping search." }),
        mkt: Type.Optional(Type.String({ description: "The market where the results come from (e.g. `en-US`). Typically, mkt is the country where the user is making the request from. However, it could be a different country if the user is not located in a country where Bing Shopping API delivers results. The market must be in the form -. For example, en-US. The string is case insensitive. For a list of possible market values, see Market Codes. NOTE: If known, you are encouraged to always specify the market. Specifying the market helps Bing route the request and return an appropriate and optimal response. If you specify a market that is not listed in Market Codes, Bing Shopping API uses a best fit market code based on an internal mapping that is subject to change. This parameter and the cc query parameter are mutually exclusive—do not specify both.. Valid values include: es-ar, en-au, de-at, nl-be, fr-be, pt-br, en-ca, fr-ca, es-cl, da-dk, and 28 more" })),
        cc: Type.Optional(Type.String({ description: "Parameter defines the country to search from. It follows the 2-character ISO\\_3166-1 format. (e.g., `us` for United States, `de` for Germany, `gb` for United Kingdom, etc.).. Valid values include: AR, AU, AT, BE, BR, CA, CL, DK, FI, FR, and 26 more" })),
        efirst: Type.Optional(Type.Number({ description: "Parameter controls the offset of the shopping results. (e.g., `efirst=10` will move the 10th shopping result to the first position)." })),
        filters: Type.Optional(Type.String({ description: "Parameter allows usage of a more complex filtering options such as filtering by date range `ex1:\"ez5_18169_18230\"` or using a specific display filters such as `ufn:\"Wunderman+Thompson\"+sid:\"5bede9a2-1bda-9887-e6eb-30b1b8b6b513\"+catguid:\"5bede9a2-1bda-9887-e6eb-30b1b8b6b513_cfb02057\"+segment:\"generic.carousel\"+entitysegment:\"Organization\"`. Exact values can be constructed by using Bing search and copying `filters` query parameter." })),
        device: Type.Optional(Type.String({ description: "Parameter defines the device to use to get the results. It can be set to `desktop` (default) to use a regular browser, `tablet` to use a tablet browser (currently using iPads), or `mobile` to use a mobile browser." })),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing Shopping results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing Shopping search results" }))
      .summary("Bing Shopping")
      .description("Search via Bing Shopping. Real API: GET /search.json?engine=bing_shopping")
      .operationId("searchBingShopping")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_shopping")
      .extension("x-serpapi-real-path", "/search.json")

    g.get("/bing_videos")
      .query(Type.Object({
        q: Type.String({ description: "Parameter defines the search query. You can use anything that you would use in a regular Bing Videos search." }),
        mkt: Type.Optional(Type.String({ description: "The market where the results come from (e.g. `en-US`). Typically, mkt is the country where the user is making the request from. However, it could be a different country if the user is not located in a country where Bing Videos API delivers results. The market must be in the form -. For example, en-US. The string is case insensitive. For a list of possible market values, see Market Codes. NOTE: If known, you are encouraged to always specify the market. Specifying the market helps Bing route the request and return an appropriate and optimal response. If you specify a market that is not listed in Market Codes, Bing Videos API uses a best fit market code based on an internal mapping that is subject to change. This parameter and the cc query parameter are mutually exclusive—do not specify both.. Valid values include: es-ar, en-au, de-at, nl-be, fr-be, pt-br, en-ca, fr-ca, es-cl, da-dk, and 28 more" })),
        cc: Type.Optional(Type.String({ description: "Parameter defines the country to search from. It follows the 2-character ISO\\_3166-1 format. (e.g., `us` for United States, `de` for Germany, `gb` for United Kingdom, etc.).. Valid values include: AR, AU, AT, BE, BR, CA, CL, DK, FI, FR, and 26 more" })),
        setlang: Type.Optional(Type.String({ description: "Parameter defines the language to search with. It follows the 2-character ISO\\_3166-1 format. (e.g., `us` for United States, `de` for Germany, `gb` for United Kingdom, etc.). You can view all valid language codes here.. Valid values include: ar, eu, bn, bg, ca, zh-hans, zh-hant, hr, cs, da, and 40 more" })),
        first: Type.Optional(Type.Number({ description: "Parameter controls the offset of the organic results. This parameter defaults to `1`. (e.g., `first=10` will move the 10th organic result to the first position)." })),
        length: Type.Optional(Type.Union([Type.Literal("short"), Type.Literal("medium"), Type.Literal("long")], { description: "Parameter is used for filtering videos by duration. It can be set to: `short` - Short (less than 5 minutes) `medium` - Medium (5-20 minutes) `long` - Long (more than 20 minutes)" })),
        date: Type.Optional(Type.Union([Type.Literal("lt1440"), Type.Literal("lt10080"), Type.Literal("lt43200"), Type.Literal("lt525600")], { description: "Parameter is used for filtering videos by date. It can be set to: `lt1440` - Past 24 hours `lt10080` - Past week `lt43200` - Past month `lt525600` - Past year" })),
        resolution: Type.Optional(Type.Union([Type.Literal("lowerthan_360p"), Type.Literal("360p"), Type.Literal("480p"), Type.Literal("720p"), Type.Literal("1080p")], { description: "Parameter is used for filtering videos by resolution type. It can be set to: `lowerthan_360p` - Lower than 360p `360p` - 360p or higher `480p` - 480p or higher `720p` - 720p or higher `1080p` - 1080p or higher" })),
        source_site: Type.Optional(Type.Union([Type.Literal("dailymotion.com"), Type.Literal("vimeo.com"), Type.Literal("metacafe.com"), Type.Literal("hulu.com"), Type.Literal("vevo.com"), Type.Literal("myspace.com"), Type.Literal("mtv.com"), Type.Literal("cbsnews.com"), Type.Literal("foxnews.com"), Type.Literal("cnn.com"), Type.Literal("msn.com")], { description: "Parameter is used for filtering videos by source. It can be set to: `dailymotion.com` - DailyMotion `vimeo.com` - Vimeo `metacafe.com` - Metacafe `hulu.com` - Hulu `vevo.com` - VEVO `myspace.com` - Myspace `mtv.com` - MTV `cbsnews.com` - CBS `foxnews.com` - FOX `cnn.com` - CNN `msn.com` - MSN" })),
        price: Type.Optional(Type.Union([Type.Literal("free"), Type.Literal("paid")], { description: "Parameter is used for filtering videos by price. It can be set to: `free` - Free `paid` - Paid" })),
        device: Type.Optional(Type.String({ description: "Parameter defines the device to use to get the results. It can be set to `desktop` (default) to use a regular browser, `tablet` to use a tablet browser (currently using iPads), or `mobile` to use a mobile browser." })),
        no_cache: Type.Optional(Type.Boolean({ description: "Parameter will force SerpApi to fetch the Bing Videos results even if a cached version is already present. A cache is served only if the query and all parameters are exactly the same. Cache expires after 1h. Cached searches are free, and are not counted towards your searches per month. It can be set to `false` (default) to allow results from the cache, or `true` to disallow results from the cache. no\\_cache and async parameters should not be used together." })),
        async: Type.Optional(Type.String({ description: "Parameter defines the way you want to submit your search to SerpApi. It can be set to `false` (default) to open an HTTP connection and keep it open until you got your search results, or `true` to just submit your search to SerpApi and retrieve them later. In this case, you'll need to use our Searches Archive API to retrieve your results. async and no\\_cache parameters should not be used together. async should not be used on accounts with Ludicrous Speed enabled." })),
        zero_trace: Type.Optional(Type.String({ description: "Enterprise only. Parameter enables ZeroTrace mode. It can be set to `false` (default) or `true`. Enable this mode to skip storing search parameters, search files, and search metadata on our servers. This may make debugging more difficult." })),
        output: Type.Optional(Type.String({ description: "Parameter defines the final output you want. It can be set to json (default) to get a structured `JSON` of the results, or `html` to get the raw html retrieved." })),
        json_restrictor: Type.Optional(Type.String({ description: "Parameter defines the fields you want to restrict in the outputs for smaller, faster responses. See JSON Restrictor for more details." })),
      }))
      .response(Type.Unknown({ description: "Bing Videos search results" }))
      .summary("Bing Videos")
      .description("Search via Bing Videos. Real API: GET /search.json?engine=bing_videos")
      .operationId("searchBingVideos")
      .tag("Bing")
      .extension("x-serpapi-engine", "bing_videos")
      .extension("x-serpapi-real-path", "/search.json")

  })
}
