import { Type } from "@sinclair/typebox"
import { named } from "spac"
import { DlpMessages } from "../shared/schemas"

export const DnssecDeleteDnssecResponseSingle = named(
  "dnssec_delete_dnssec_response_single",
  Type.Object({
    errors: DlpMessages,
    messages: DlpMessages,
    success: Type.Union([Type.Literal(true)], { description: "Whether the API call was successful." }),
    result: Type.Optional(Type.String()),
  }),
)

export const DnssecStatus = named(
  "dnssec_status",
  Type.Union(
    [
      Type.Literal("active"),
      Type.Literal("pending"),
      Type.Literal("disabled"),
      Type.Literal("pending-disabled"),
      Type.Literal("error"),
    ],
    {
      description: "Status of DNSSEC, based on user-desired state and presence of necessary records.",
      "x-auditable": true,
    },
  ),
)

export const DnssecPublicKey = named(
  "dnssec_public_key",
  Type.Union([
    Type.String({ description: "Public key for DS record.", readOnly: true, "x-auditable": true }),
    Type.Null(),
  ]),
)

export const DnssecModifiedOn = named(
  "dnssec_modified_on",
  Type.Union([
    Type.String({
      description: "When DNSSEC was last modified.",
      format: "date-time",
      readOnly: true,
      "x-auditable": true,
    }),
    Type.Null(),
  ]),
)

export const DnssecKeyType = named(
  "dnssec_key_type",
  Type.Union([Type.String({ description: "Algorithm key type.", readOnly: true, "x-auditable": true }), Type.Null()]),
)

export const DnssecKeyTag = named(
  "dnssec_key_tag",
  Type.Union([Type.Number({ description: "Code for key tag.", readOnly: true, "x-auditable": true }), Type.Null()]),
)

export const DnssecFlags = named(
  "dnssec_flags",
  Type.Union([
    Type.Number({ description: "Flag for DNSSEC record.", readOnly: true, "x-auditable": true }),
    Type.Null(),
  ]),
)

export const DnssecDs = named(
  "dnssec_ds",
  Type.Union([Type.String({ description: "Full DS record.", readOnly: true, "x-auditable": true }), Type.Null()]),
)

export const DnssecDnssecUseNsec3 = named(
  "dnssec_dnssec_use_nsec3",
  Type.Boolean({
    description:
      "If true, enables the use of NSEC3 together with DNSSEC on the zone.\nCombined with setting dnssec_presigned to true, this enables the use of\nNSEC3 records when transferring in from an external provider.\nIf dnssec_presigned is instead set to false (default), NSEC3 records will be\ngenerated and signed at request time.\n\nSee [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.",
    "x-auditable": true,
  }),
)

export const DnssecDnssecPresigned = named(
  "dnssec_dnssec_presigned",
  Type.Boolean({
    description:
      "If true, allows Cloudflare to transfer in a DNSSEC-signed zone\nincluding signatures from an external provider, without requiring\nCloudflare to sign any records on the fly.\n\nNote that this feature has some limitations.\nSee [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.",
    "x-auditable": true,
  }),
)

export const DnssecDnssecMultiSigner = named(
  "dnssec_dnssec_multi_signer",
  Type.Boolean({
    description:
      "If true, multi-signer DNSSEC is enabled on the zone, allowing multiple\nproviders to serve a DNSSEC-signed zone at the same time.\nThis is required for DNSKEY records (except those automatically\ngenerated by Cloudflare) to be added to the zone.\n\nSee [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.",
    "x-auditable": true,
  }),
)

export const DnssecDigestType = named(
  "dnssec_digest_type",
  Type.Union([
    Type.String({ description: "Coded type for digest algorithm.", readOnly: true, "x-auditable": true }),
    Type.Null(),
  ]),
)

export const DnssecDigestAlgorithm = named(
  "dnssec_digest_algorithm",
  Type.Union([
    Type.String({ description: "Type of digest algorithm.", readOnly: true, "x-auditable": true }),
    Type.Null(),
  ]),
)

export const DnssecDigest = named(
  "dnssec_digest",
  Type.Union([Type.String({ description: "Digest hash.", readOnly: true, "x-auditable": true }), Type.Null()]),
)

export const DnssecAlgorithm = named(
  "dnssec_algorithm",
  Type.Union([Type.String({ description: "Algorithm key code.", readOnly: true, "x-auditable": true }), Type.Null()]),
)

export const DnssecDnssec = named(
  "dnssec_dnssec",
  Type.Object({
    algorithm: Type.Optional(DnssecAlgorithm),
    digest: Type.Optional(DnssecDigest),
    digest_algorithm: Type.Optional(DnssecDigestAlgorithm),
    digest_type: Type.Optional(DnssecDigestType),
    dnssec_multi_signer: Type.Optional(DnssecDnssecMultiSigner),
    dnssec_presigned: Type.Optional(DnssecDnssecPresigned),
    dnssec_use_nsec3: Type.Optional(DnssecDnssecUseNsec3),
    ds: Type.Optional(DnssecDs),
    flags: Type.Optional(DnssecFlags),
    key_tag: Type.Optional(DnssecKeyTag),
    key_type: Type.Optional(DnssecKeyType),
    modified_on: Type.Optional(DnssecModifiedOn),
    public_key: Type.Optional(DnssecPublicKey),
    status: Type.Optional(DnssecStatus),
  }),
)

export const DnssecDnssecResponseSingle = named(
  "dnssec_dnssec_response_single",
  Type.Object({
    errors: DlpMessages,
    messages: DlpMessages,
    success: Type.Union([Type.Literal(true)], { description: "Whether the API call was successful." }),
    result: Type.Optional(DnssecDnssec),
  }),
)
